### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Sarthak88-tech**
Added new card for Machine Learning resources.

### CODE REVIEW

**Comment by Nitesh-thapliyal** [comment]
Hey @Sarthak88-tech can you resolve the conflict

**Comment by Sarthak88-tech** [comment]
I have resolved the conflicts. From: Nitesh ThapliyalSent: 03 October 2022 08:04To: Bauddhik-Geeks/Resource-CardCc: Sarthak Wakchaure; MentionSubject: Re: [Bauddhik-Geeks/Resource-Card] Update index.html (PR #23) Hey @Sarthak88-tech can you resolve the conflict—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Rajkumar-justcoder** [comment]
What?

**Comment by Sarthak88-tech** [comment]
Sir, I have resolved the conflict in index.html file. Please merge it. From: Rajkumar KhistariyaSent: 03 October 2022 09:22To: Bauddhik-Geeks/Resource-CardCc: Sarthak Wakchaure; MentionSubject: Re: [Bauddhik-Geeks/Resource-Card] Update index.html (PR #23) What?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Rajkumar-justcoder** [comment]
Okay will check it soon

**Pull request merged**
