### PR TITLE
feat: added my personal card

### PR DESCRIPTION
**Pull request by ialexanderbrito**

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Instead of sharing your portfolio and Instagram link, do share helpful learning resources

**Comment by ialexanderbrito** [comment]
I updated the links

**Comment by Nitesh-thapliyal** [comment]
@ialexanderbrito Please resolve the conflict after that I will merge the PR

**Comment by ialexanderbrito** [comment]
@Nitesh-thapliyal I resolve the conflict :D

**Review by Nitesh-thapliyal — APPROVED** [review]

**Pull request merged**
