### PR TITLE
added useful resources

### PR DESCRIPTION
**Pull request by SumitKanth**
Successfully added 3 usefull resources.

### CODE REVIEW

**Comment by itsvipindev** [comment]
sir please review the PR and merge 
with hacktoberfest label

**Comment by Rajkumar-justcoder** [comment]
hey there,
can you confrom that the links are not  reffral links

**Comment by SumitKanth** [comment]
@Rajkumar-justcoder Yes it has reffral links, what to do now ?

**Comment by Rajkumar-justcoder** [comment]
> @Rajkumar-justcoder Yes it has reffral links, what to do now ?

so u can remove ref links and add normal one pls

**Comment by SumitKanth** [comment]
> > @Rajkumar-justcoder Yes it has reffral links, what to do now ?
> 
> so u can remove ref links and add normal one pls

okii will do this, thanks

**Comment by Rajkumar-justcoder** [comment]
> > > @Rajkumar-justcoder Yes it has reffral links, what to do now ?
> > 
> > 
> > so u can remove ref links and add normal one pls
> 
> okii will do this, thanks



> > > @Rajkumar-justcoder Yes it has reffral links, what to do now ?
> > 
> > 
> > so u can remove ref links and add normal one pls
> 
> okii will do this, thanks

also check that ig any conflict comes casue we are merging pr now so

**Comment by SumitKanth** [comment]
@Rajkumar-justcoder I am doing changes, Can I close this pr and make new pr ?

**Comment by Rajkumar-justcoder** [comment]
> @Rajkumar-justcoder I am doing changes, Can I close this pr and make new pr ?

yeah have merged one pr so yeah

**Comment by SumitKanth** [comment]
@Rajkumar-justcoder not got what you said ?

**Comment by Rajkumar-justcoder** [comment]
> @Rajkumar-justcoder not got what you said ?

yeah close this pr cause i have merged one pr so it will be conflict

**Comment by Rajkumar-justcoder** [comment]
nvm its not

**Comment by Rajkumar-justcoder** [comment]
LGTM!! Thanks :rocket:

**Pull request merged**
