### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by SumitKanth**
Added favicon in website.

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
@Nitesh-thapliyal  Pls check favicon icon

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal can you plz review it.

**Comment by Nitesh-thapliyal** [comment]
> @Nitesh-thapliyal can you plz review it.

I have already reviewed it and I asked you to change the format of image to svg

**Comment by SumitKanth** [comment]
> > @Nitesh-thapliyal can you plz review it.
> 
> I have already reviewed it and I asked you to change the format of image to svg

okk will do this, thanks

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal changed the format, now you can review it

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal sirr plz review it

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Use the SVG image instead of JPG and PNG

**Comment by SumitKanth** [comment]
Screenshot (556)

@Nitesh-thapliyal now ?

**Comment by Nitesh-thapliyal** [comment]
> Screenshot (556)
> 
> @Nitesh-thapliyal now ?

Yup, now it looks great!

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal can you review it

**Pull request merged**
